---
  - name: Echo the path
    shell: echo $PATH 1>&2

  - name: Add the virtualbox and vagrant packages (Ubuntu)
    when: ansible_os_family == 'Debian'
    apt: name="$item" state=present
    with_items:
      - virtualbox

  - name: Add the vagrant package on the main web site (Ubuntu)
    when: ansible_os_family == 'Debian'
    shell: dpkg --status vagrant 2>/dev/null || dpkg -i {{ vagrant_debian_url }}

  #- name: Remove vagrant package prior to doing the gem package (Ubuntu)
  #  when: ansible_os_family == 'Debian'
  #  apt: name="vagrant" state=absent

  #- name: Install Vagrant GEM package
  #  gem: name="vagrant" state="present"

# RedHat setup 
  - name: Install the VirtualBox RPM if not already installed (RedHat)
    when: ansible_os_family == 'RedHat'
    shell: rpm -q VirtualBox || rpm -Uvh {{ vbox_redhat_url }}


  - name: Install the Vagrant RPM (RedHat)
    when: ansible_os_family == 'RedHat'
    shell: rpm -q vagrant || rpm -Uvh {{ vagrant_redhat_url }}

