---
  - name: Echo the path
    shell: echo $PATH 1>&2

  - name: Add the virtualbox and vagrant packages (Ubuntu)
    when: ansible_os_family == 'Debian'
    apt: name="$item" state=present
    with_items:
      - vagrant
      - virtualbox

  - name: Remove vagrant package prior to doing the gem package (Ubuntu)
    when: ansible_os_family == 'Debian'
    apt: name="vagrant" state=absent

  - name: Install Vagrant GEM package
    gem: name="vagrant" state="present"

# RedHat setup
#  - name: update rsyslog config to forward to buckbeak
#    when: ansible_os_family == 'RedHat'
#    template: src="10-logserver.conf" dest="/etc/rsyslog.d/10-logserver.conf"
#    notify:
#      - restart debian rsyslog

#  - name: Ensure that Debian/Ubuntu base packages are installed
#    when: ansible_os_family == 'RedHat'
#    apt: name="$item" state=present
#    with_items:
#      - vim
#      - git
#      - csh

